package com.uis;

import com.view.Menu;

/**
 * This class displays help to the user on how to operate this program.
 *
 * @author Casper
 */
public class HelpMenu extends com.view.Menu {

    // The menu to return to.
    private Menu menu;

    /**
     * Creates new form HelpMenu. Meant for debugging.
     */
    public HelpMenu() {
        initComponents();
    }

    /**
     * Creates new form HelpMenu that can send you back from where you came
     * from.
     */
    public HelpMenu(Menu m) {
        initComponents();
        menu = m;
        setScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("The PlayPillow 1.0 - Help");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jButton2.setText("Sluiten");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 120, 54));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel2.setText("<html><h2>Uitleg over The PlayPillow");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel3.setText("Dit programma is gemaakt om de modi te veranderen van de PlayPillow. U kunt dit eenvoudig doen ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel4.setText("zullen aanwijzingen volgen die u door het process heen helpen.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel5.setText("door op bij het hoofdmenu op modes te klikken en vervolgens een mode te selecteren. Daarna ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel6.setText("<htmL><h3>Wat is een COM poort?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel7.setText("Een COM poort is eenvoudig weg een USB-ingang op uw computer. Gebruik de meegeleverde kabel ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel8.setText("om in uw computer te pluggen.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jButton3.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jButton3.setText("Terug");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 120, 54));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/GUIMenu.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
